//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceWSPrueba.wsconsulta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bataperu.com.pe/", ConfigurationName="wsconsulta.Sunat_Reniec_PESoap")]
    public interface Sunat_Reniec_PESoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje ws_persona_reniecRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://bataperu.com.pe/ws_persona_reniec", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceWSPrueba.wsconsulta.ws_persona_reniecResponse ws_persona_reniec(ServiceWSPrueba.wsconsulta.ws_persona_reniecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bataperu.com.pe/ws_persona_reniec", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceWSPrueba.wsconsulta.ws_persona_reniecResponse> ws_persona_reniecAsync(ServiceWSPrueba.wsconsulta.ws_persona_reniecRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje ws_persona_sunatRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://bataperu.com.pe/ws_persona_sunat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceWSPrueba.wsconsulta.ws_persona_sunatResponse ws_persona_sunat(ServiceWSPrueba.wsconsulta.ws_persona_sunatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bataperu.com.pe/ws_persona_sunat", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceWSPrueba.wsconsulta.ws_persona_sunatResponse> ws_persona_sunatAsync(ServiceWSPrueba.wsconsulta.ws_persona_sunatRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bataperu.com.pe/")]
    public partial class validateLogin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bataperu.com.pe/")]
    public partial class SunatValida : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string estadoField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bataperu.com.pe/")]
    public partial class DataSunat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SunatValida valida_SunatField;
        
        private string rucField;
        
        private string razon_SocialField;
        
        private string direccionField;
        
        private string telefonoField;
        
        private string estadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SunatValida Valida_Sunat {
            get {
                return this.valida_SunatField;
            }
            set {
                this.valida_SunatField = value;
                this.RaisePropertyChanged("Valida_Sunat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ruc {
            get {
                return this.rucField;
            }
            set {
                this.rucField = value;
                this.RaisePropertyChanged("Ruc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Razon_Social {
            get {
                return this.razon_SocialField;
            }
            set {
                this.razon_SocialField = value;
                this.RaisePropertyChanged("Razon_Social");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("Direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bataperu.com.pe/")]
    public partial class ReniecValida : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string estadoField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bataperu.com.pe/")]
    public partial class DataReniec : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ReniecValida valida_ReniecField;
        
        private string dniField;
        
        private string nombresField;
        
        private string apePatField;
        
        private string apeMatField;
        
        private string estadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ReniecValida Valida_Reniec {
            get {
                return this.valida_ReniecField;
            }
            set {
                this.valida_ReniecField = value;
                this.RaisePropertyChanged("Valida_Reniec");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("Dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("Nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ApePat {
            get {
                return this.apePatField;
            }
            set {
                this.apePatField = value;
                this.RaisePropertyChanged("ApePat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ApeMat {
            get {
                return this.apeMatField;
            }
            set {
                this.apeMatField = value;
                this.RaisePropertyChanged("ApeMat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_persona_reniec", WrapperNamespace="http://bataperu.com.pe/", IsWrapped=true)]
    public partial class ws_persona_reniecRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://bataperu.com.pe/")]
        public ServiceWSPrueba.wsconsulta.validateLogin validateLogin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bataperu.com.pe/", Order=0)]
        public string nro_dni;
        
        public ws_persona_reniecRequest() {
        }
        
        public ws_persona_reniecRequest(ServiceWSPrueba.wsconsulta.validateLogin validateLogin, string nro_dni) {
            this.validateLogin = validateLogin;
            this.nro_dni = nro_dni;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_persona_reniecResponse", WrapperNamespace="http://bataperu.com.pe/", IsWrapped=true)]
    public partial class ws_persona_reniecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bataperu.com.pe/", Order=0)]
        public ServiceWSPrueba.wsconsulta.DataReniec ws_persona_reniecResult;
        
        public ws_persona_reniecResponse() {
        }
        
        public ws_persona_reniecResponse(ServiceWSPrueba.wsconsulta.DataReniec ws_persona_reniecResult) {
            this.ws_persona_reniecResult = ws_persona_reniecResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_persona_sunat", WrapperNamespace="http://bataperu.com.pe/", IsWrapped=true)]
    public partial class ws_persona_sunatRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://bataperu.com.pe/")]
        public ServiceWSPrueba.wsconsulta.validateLogin validateLogin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bataperu.com.pe/", Order=0)]
        public string nro_ruc;
        
        public ws_persona_sunatRequest() {
        }
        
        public ws_persona_sunatRequest(ServiceWSPrueba.wsconsulta.validateLogin validateLogin, string nro_ruc) {
            this.validateLogin = validateLogin;
            this.nro_ruc = nro_ruc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_persona_sunatResponse", WrapperNamespace="http://bataperu.com.pe/", IsWrapped=true)]
    public partial class ws_persona_sunatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bataperu.com.pe/", Order=0)]
        public ServiceWSPrueba.wsconsulta.DataSunat ws_persona_sunatResult;
        
        public ws_persona_sunatResponse() {
        }
        
        public ws_persona_sunatResponse(ServiceWSPrueba.wsconsulta.DataSunat ws_persona_sunatResult) {
            this.ws_persona_sunatResult = ws_persona_sunatResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Sunat_Reniec_PESoapChannel : ServiceWSPrueba.wsconsulta.Sunat_Reniec_PESoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Sunat_Reniec_PESoapClient : System.ServiceModel.ClientBase<ServiceWSPrueba.wsconsulta.Sunat_Reniec_PESoap>, ServiceWSPrueba.wsconsulta.Sunat_Reniec_PESoap {
        
        public Sunat_Reniec_PESoapClient() {
        }
        
        public Sunat_Reniec_PESoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Sunat_Reniec_PESoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Sunat_Reniec_PESoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Sunat_Reniec_PESoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWSPrueba.wsconsulta.ws_persona_reniecResponse ServiceWSPrueba.wsconsulta.Sunat_Reniec_PESoap.ws_persona_reniec(ServiceWSPrueba.wsconsulta.ws_persona_reniecRequest request) {
            return base.Channel.ws_persona_reniec(request);
        }
        
        public ServiceWSPrueba.wsconsulta.DataReniec ws_persona_reniec(ServiceWSPrueba.wsconsulta.validateLogin validateLogin, string nro_dni) {
            ServiceWSPrueba.wsconsulta.ws_persona_reniecRequest inValue = new ServiceWSPrueba.wsconsulta.ws_persona_reniecRequest();
            inValue.validateLogin = validateLogin;
            inValue.nro_dni = nro_dni;
            ServiceWSPrueba.wsconsulta.ws_persona_reniecResponse retVal = ((ServiceWSPrueba.wsconsulta.Sunat_Reniec_PESoap)(this)).ws_persona_reniec(inValue);
            return retVal.ws_persona_reniecResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceWSPrueba.wsconsulta.ws_persona_reniecResponse> ServiceWSPrueba.wsconsulta.Sunat_Reniec_PESoap.ws_persona_reniecAsync(ServiceWSPrueba.wsconsulta.ws_persona_reniecRequest request) {
            return base.Channel.ws_persona_reniecAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceWSPrueba.wsconsulta.ws_persona_reniecResponse> ws_persona_reniecAsync(ServiceWSPrueba.wsconsulta.validateLogin validateLogin, string nro_dni) {
            ServiceWSPrueba.wsconsulta.ws_persona_reniecRequest inValue = new ServiceWSPrueba.wsconsulta.ws_persona_reniecRequest();
            inValue.validateLogin = validateLogin;
            inValue.nro_dni = nro_dni;
            return ((ServiceWSPrueba.wsconsulta.Sunat_Reniec_PESoap)(this)).ws_persona_reniecAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWSPrueba.wsconsulta.ws_persona_sunatResponse ServiceWSPrueba.wsconsulta.Sunat_Reniec_PESoap.ws_persona_sunat(ServiceWSPrueba.wsconsulta.ws_persona_sunatRequest request) {
            return base.Channel.ws_persona_sunat(request);
        }
        
        public ServiceWSPrueba.wsconsulta.DataSunat ws_persona_sunat(ServiceWSPrueba.wsconsulta.validateLogin validateLogin, string nro_ruc) {
            ServiceWSPrueba.wsconsulta.ws_persona_sunatRequest inValue = new ServiceWSPrueba.wsconsulta.ws_persona_sunatRequest();
            inValue.validateLogin = validateLogin;
            inValue.nro_ruc = nro_ruc;
            ServiceWSPrueba.wsconsulta.ws_persona_sunatResponse retVal = ((ServiceWSPrueba.wsconsulta.Sunat_Reniec_PESoap)(this)).ws_persona_sunat(inValue);
            return retVal.ws_persona_sunatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceWSPrueba.wsconsulta.ws_persona_sunatResponse> ServiceWSPrueba.wsconsulta.Sunat_Reniec_PESoap.ws_persona_sunatAsync(ServiceWSPrueba.wsconsulta.ws_persona_sunatRequest request) {
            return base.Channel.ws_persona_sunatAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceWSPrueba.wsconsulta.ws_persona_sunatResponse> ws_persona_sunatAsync(ServiceWSPrueba.wsconsulta.validateLogin validateLogin, string nro_ruc) {
            ServiceWSPrueba.wsconsulta.ws_persona_sunatRequest inValue = new ServiceWSPrueba.wsconsulta.ws_persona_sunatRequest();
            inValue.validateLogin = validateLogin;
            inValue.nro_ruc = nro_ruc;
            return ((ServiceWSPrueba.wsconsulta.Sunat_Reniec_PESoap)(this)).ws_persona_sunatAsync(inValue);
        }
    }
}
