//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBata_WS_Interfaces.BataTransac {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bataperu.com.pe/", ConfigurationName="BataTransac.Bata_TransactionSoap")]
    public interface Bata_TransactionSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje HelloWorldRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://bataperu.com.pe/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppBata_WS_Interfaces.BataTransac.HelloWorldResponse HelloWorld(AppBata_WS_Interfaces.BataTransac.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bataperu.com.pe/fvdespc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppBata_WS_Interfaces.BataTransac.Ent_Fvdespc fvdespc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bataperu.com.pe/scdddes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppBata_WS_Interfaces.BataTransac.Ent_Scdddes scdddes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bataperu.com.pe/pathdbf", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppBata_WS_Interfaces.BataTransac.Ent_PathDBF pathdbf();
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje ws_update_transaction_guiasRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://bataperu.com.pe/ws_update_transaction_guias", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppBata_WS_Interfaces.BataTransac.ws_update_transaction_guiasResponse ws_update_transaction_guias(AppBata_WS_Interfaces.BataTransac.ws_update_transaction_guiasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje ws_errores_transactionRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://bataperu.com.pe/ws_errores_transaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppBata_WS_Interfaces.BataTransac.ws_errores_transactionResponse ws_errores_transaction(AppBata_WS_Interfaces.BataTransac.ws_errores_transactionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje ws_get_location_dbfRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://bataperu.com.pe/ws_get_location_dbf", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppBata_WS_Interfaces.BataTransac.ws_get_location_dbfResponse ws_get_location_dbf(AppBata_WS_Interfaces.BataTransac.ws_get_location_dbfRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bataperu.com.pe/")]
    public partial class ValidateAcceso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bataperu.com.pe/")]
    public partial class Ent_PathDBF : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rutloc_namedbfField;
        
        private string rutloc_locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string rutloc_namedbf {
            get {
                return this.rutloc_namedbfField;
            }
            set {
                this.rutloc_namedbfField = value;
                this.RaisePropertyChanged("rutloc_namedbf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string rutloc_location {
            get {
                return this.rutloc_locationField;
            }
            set {
                this.rutloc_locationField = value;
                this.RaisePropertyChanged("rutloc_location");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bataperu.com.pe/")]
    public partial class Ent_Scdddes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dDES_TIPOField;
        
        private string dDES_ALMACField;
        
        private string dDES_GUIREField;
        
        private string dDES_NDESPField;
        
        private string dDES_MFDESField;
        
        private string dDES_DESTIField;
        
        private string dDES_N_INIField;
        
        private string dDES_N_FINField;
        
        private string dDES_CPAGOField;
        
        private System.DateTime dDES_FEMBAField;
        
        private System.DateTime dDES_FECHAField;
        
        private System.DateTime dDES_FDESPField;
        
        private string dDES_ESTADField;
        
        private string dDES_GGUIAField;
        
        private string dDES_CCONDField;
        
        private decimal dDES_CALZField;
        
        private decimal dDES_NCALZField;
        
        private decimal dDES_TOCAJField;
        
        private string dDES_IMPREField;
        
        private string dDES_GVALOField;
        
        private string dDES_SUBGRField;
        
        private string dDES_RUCTCField;
        
        private string dDES_TRANSField;
        
        private string dDES_TRAN2Field;
        
        private string dDES_OBSERField;
        
        private string dDES_NOMTCField;
        
        private string dDES_NGUIAField;
        
        private string dDES_NRLIQField;
        
        private string dDES_LIMPRField;
        
        private string dDES_EMPREField;
        
        private string dDES_CANALField;
        
        private string dDES_CADENField;
        
        private string dDES_SECCIField;
        
        private string dDES_FTXField;
        
        private string dDES_FTXTDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DDES_TIPO {
            get {
                return this.dDES_TIPOField;
            }
            set {
                this.dDES_TIPOField = value;
                this.RaisePropertyChanged("DDES_TIPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DDES_ALMAC {
            get {
                return this.dDES_ALMACField;
            }
            set {
                this.dDES_ALMACField = value;
                this.RaisePropertyChanged("DDES_ALMAC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DDES_GUIRE {
            get {
                return this.dDES_GUIREField;
            }
            set {
                this.dDES_GUIREField = value;
                this.RaisePropertyChanged("DDES_GUIRE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DDES_NDESP {
            get {
                return this.dDES_NDESPField;
            }
            set {
                this.dDES_NDESPField = value;
                this.RaisePropertyChanged("DDES_NDESP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DDES_MFDES {
            get {
                return this.dDES_MFDESField;
            }
            set {
                this.dDES_MFDESField = value;
                this.RaisePropertyChanged("DDES_MFDES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DDES_DESTI {
            get {
                return this.dDES_DESTIField;
            }
            set {
                this.dDES_DESTIField = value;
                this.RaisePropertyChanged("DDES_DESTI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DDES_N_INI {
            get {
                return this.dDES_N_INIField;
            }
            set {
                this.dDES_N_INIField = value;
                this.RaisePropertyChanged("DDES_N_INI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DDES_N_FIN {
            get {
                return this.dDES_N_FINField;
            }
            set {
                this.dDES_N_FINField = value;
                this.RaisePropertyChanged("DDES_N_FIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string DDES_CPAGO {
            get {
                return this.dDES_CPAGOField;
            }
            set {
                this.dDES_CPAGOField = value;
                this.RaisePropertyChanged("DDES_CPAGO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime DDES_FEMBA {
            get {
                return this.dDES_FEMBAField;
            }
            set {
                this.dDES_FEMBAField = value;
                this.RaisePropertyChanged("DDES_FEMBA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public System.DateTime DDES_FECHA {
            get {
                return this.dDES_FECHAField;
            }
            set {
                this.dDES_FECHAField = value;
                this.RaisePropertyChanged("DDES_FECHA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.DateTime DDES_FDESP {
            get {
                return this.dDES_FDESPField;
            }
            set {
                this.dDES_FDESPField = value;
                this.RaisePropertyChanged("DDES_FDESP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DDES_ESTAD {
            get {
                return this.dDES_ESTADField;
            }
            set {
                this.dDES_ESTADField = value;
                this.RaisePropertyChanged("DDES_ESTAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string DDES_GGUIA {
            get {
                return this.dDES_GGUIAField;
            }
            set {
                this.dDES_GGUIAField = value;
                this.RaisePropertyChanged("DDES_GGUIA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string DDES_CCOND {
            get {
                return this.dDES_CCONDField;
            }
            set {
                this.dDES_CCONDField = value;
                this.RaisePropertyChanged("DDES_CCOND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public decimal DDES_CALZ {
            get {
                return this.dDES_CALZField;
            }
            set {
                this.dDES_CALZField = value;
                this.RaisePropertyChanged("DDES_CALZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public decimal DDES_NCALZ {
            get {
                return this.dDES_NCALZField;
            }
            set {
                this.dDES_NCALZField = value;
                this.RaisePropertyChanged("DDES_NCALZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public decimal DDES_TOCAJ {
            get {
                return this.dDES_TOCAJField;
            }
            set {
                this.dDES_TOCAJField = value;
                this.RaisePropertyChanged("DDES_TOCAJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string DDES_IMPRE {
            get {
                return this.dDES_IMPREField;
            }
            set {
                this.dDES_IMPREField = value;
                this.RaisePropertyChanged("DDES_IMPRE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string DDES_GVALO {
            get {
                return this.dDES_GVALOField;
            }
            set {
                this.dDES_GVALOField = value;
                this.RaisePropertyChanged("DDES_GVALO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string DDES_SUBGR {
            get {
                return this.dDES_SUBGRField;
            }
            set {
                this.dDES_SUBGRField = value;
                this.RaisePropertyChanged("DDES_SUBGR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string DDES_RUCTC {
            get {
                return this.dDES_RUCTCField;
            }
            set {
                this.dDES_RUCTCField = value;
                this.RaisePropertyChanged("DDES_RUCTC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string DDES_TRANS {
            get {
                return this.dDES_TRANSField;
            }
            set {
                this.dDES_TRANSField = value;
                this.RaisePropertyChanged("DDES_TRANS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string DDES_TRAN2 {
            get {
                return this.dDES_TRAN2Field;
            }
            set {
                this.dDES_TRAN2Field = value;
                this.RaisePropertyChanged("DDES_TRAN2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string DDES_OBSER {
            get {
                return this.dDES_OBSERField;
            }
            set {
                this.dDES_OBSERField = value;
                this.RaisePropertyChanged("DDES_OBSER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string DDES_NOMTC {
            get {
                return this.dDES_NOMTCField;
            }
            set {
                this.dDES_NOMTCField = value;
                this.RaisePropertyChanged("DDES_NOMTC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string DDES_NGUIA {
            get {
                return this.dDES_NGUIAField;
            }
            set {
                this.dDES_NGUIAField = value;
                this.RaisePropertyChanged("DDES_NGUIA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string DDES_NRLIQ {
            get {
                return this.dDES_NRLIQField;
            }
            set {
                this.dDES_NRLIQField = value;
                this.RaisePropertyChanged("DDES_NRLIQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string DDES_LIMPR {
            get {
                return this.dDES_LIMPRField;
            }
            set {
                this.dDES_LIMPRField = value;
                this.RaisePropertyChanged("DDES_LIMPR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string DDES_EMPRE {
            get {
                return this.dDES_EMPREField;
            }
            set {
                this.dDES_EMPREField = value;
                this.RaisePropertyChanged("DDES_EMPRE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string DDES_CANAL {
            get {
                return this.dDES_CANALField;
            }
            set {
                this.dDES_CANALField = value;
                this.RaisePropertyChanged("DDES_CANAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string DDES_CADEN {
            get {
                return this.dDES_CADENField;
            }
            set {
                this.dDES_CADENField = value;
                this.RaisePropertyChanged("DDES_CADEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string DDES_SECCI {
            get {
                return this.dDES_SECCIField;
            }
            set {
                this.dDES_SECCIField = value;
                this.RaisePropertyChanged("DDES_SECCI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string DDES_FTX {
            get {
                return this.dDES_FTXField;
            }
            set {
                this.dDES_FTXField = value;
                this.RaisePropertyChanged("DDES_FTX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string DDES_FTXTD {
            get {
                return this.dDES_FTXTDField;
            }
            set {
                this.dDES_FTXTDField = value;
                this.RaisePropertyChanged("DDES_FTXTD");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bataperu.com.pe/")]
    public partial class Ent_Fvdespc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dESC_ALMACField;
        
        private string dESC_GUDISField;
        
        private string dESC_NDESPField;
        
        private string dESC_TDESField;
        
        private System.DateTime dESC_FECHAField;
        
        private System.DateTime dESC_FDESPField;
        
        private string dESC_ESTADField;
        
        private string dESC_TIPOField;
        
        private string dESC_TORIField;
        
        private System.DateTime dESC_FEMIField;
        
        private string dESC_SEMIField;
        
        private System.DateTime dESC_FTRAField;
        
        private string dESC_NUMEField;
        
        private string dESC_CONCEField;
        
        private string dESC_NMOVCField;
        
        private string dESC_EMPREField;
        
        private string dESC_SECCIField;
        
        private string dESC_CANALField;
        
        private string dESC_CADENField;
        
        private string dESC_FTXField;
        
        private string dESC_TXPOSField;
        
        private System.Data.DataTable dT_FVDESPDField;
        
        private System.Data.DataTable dT_FVDESPD_TREGMEDIDAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DESC_ALMAC {
            get {
                return this.dESC_ALMACField;
            }
            set {
                this.dESC_ALMACField = value;
                this.RaisePropertyChanged("DESC_ALMAC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DESC_GUDIS {
            get {
                return this.dESC_GUDISField;
            }
            set {
                this.dESC_GUDISField = value;
                this.RaisePropertyChanged("DESC_GUDIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DESC_NDESP {
            get {
                return this.dESC_NDESPField;
            }
            set {
                this.dESC_NDESPField = value;
                this.RaisePropertyChanged("DESC_NDESP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DESC_TDES {
            get {
                return this.dESC_TDESField;
            }
            set {
                this.dESC_TDESField = value;
                this.RaisePropertyChanged("DESC_TDES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime DESC_FECHA {
            get {
                return this.dESC_FECHAField;
            }
            set {
                this.dESC_FECHAField = value;
                this.RaisePropertyChanged("DESC_FECHA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime DESC_FDESP {
            get {
                return this.dESC_FDESPField;
            }
            set {
                this.dESC_FDESPField = value;
                this.RaisePropertyChanged("DESC_FDESP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DESC_ESTAD {
            get {
                return this.dESC_ESTADField;
            }
            set {
                this.dESC_ESTADField = value;
                this.RaisePropertyChanged("DESC_ESTAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DESC_TIPO {
            get {
                return this.dESC_TIPOField;
            }
            set {
                this.dESC_TIPOField = value;
                this.RaisePropertyChanged("DESC_TIPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string DESC_TORI {
            get {
                return this.dESC_TORIField;
            }
            set {
                this.dESC_TORIField = value;
                this.RaisePropertyChanged("DESC_TORI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime DESC_FEMI {
            get {
                return this.dESC_FEMIField;
            }
            set {
                this.dESC_FEMIField = value;
                this.RaisePropertyChanged("DESC_FEMI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string DESC_SEMI {
            get {
                return this.dESC_SEMIField;
            }
            set {
                this.dESC_SEMIField = value;
                this.RaisePropertyChanged("DESC_SEMI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.DateTime DESC_FTRA {
            get {
                return this.dESC_FTRAField;
            }
            set {
                this.dESC_FTRAField = value;
                this.RaisePropertyChanged("DESC_FTRA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DESC_NUME {
            get {
                return this.dESC_NUMEField;
            }
            set {
                this.dESC_NUMEField = value;
                this.RaisePropertyChanged("DESC_NUME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string DESC_CONCE {
            get {
                return this.dESC_CONCEField;
            }
            set {
                this.dESC_CONCEField = value;
                this.RaisePropertyChanged("DESC_CONCE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string DESC_NMOVC {
            get {
                return this.dESC_NMOVCField;
            }
            set {
                this.dESC_NMOVCField = value;
                this.RaisePropertyChanged("DESC_NMOVC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string DESC_EMPRE {
            get {
                return this.dESC_EMPREField;
            }
            set {
                this.dESC_EMPREField = value;
                this.RaisePropertyChanged("DESC_EMPRE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string DESC_SECCI {
            get {
                return this.dESC_SECCIField;
            }
            set {
                this.dESC_SECCIField = value;
                this.RaisePropertyChanged("DESC_SECCI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string DESC_CANAL {
            get {
                return this.dESC_CANALField;
            }
            set {
                this.dESC_CANALField = value;
                this.RaisePropertyChanged("DESC_CANAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string DESC_CADEN {
            get {
                return this.dESC_CADENField;
            }
            set {
                this.dESC_CADENField = value;
                this.RaisePropertyChanged("DESC_CADEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string DESC_FTX {
            get {
                return this.dESC_FTXField;
            }
            set {
                this.dESC_FTXField = value;
                this.RaisePropertyChanged("DESC_FTX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string DESC_TXPOS {
            get {
                return this.dESC_TXPOSField;
            }
            set {
                this.dESC_TXPOSField = value;
                this.RaisePropertyChanged("DESC_TXPOS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public System.Data.DataTable DT_FVDESPD {
            get {
                return this.dT_FVDESPDField;
            }
            set {
                this.dT_FVDESPDField = value;
                this.RaisePropertyChanged("DT_FVDESPD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public System.Data.DataTable DT_FVDESPD_TREGMEDIDA {
            get {
                return this.dT_FVDESPD_TREGMEDIDAField;
            }
            set {
                this.dT_FVDESPD_TREGMEDIDAField = value;
                this.RaisePropertyChanged("DT_FVDESPD_TREGMEDIDA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bataperu.com.pe/")]
    public partial class Ent_MsgTransac : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorld", WrapperNamespace="http://bataperu.com.pe/", IsWrapped=true)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://bataperu.com.pe/")]
        public AppBata_WS_Interfaces.BataTransac.ValidateAcceso ValidateAcceso;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(AppBata_WS_Interfaces.BataTransac.ValidateAcceso ValidateAcceso) {
            this.ValidateAcceso = ValidateAcceso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorldResponse", WrapperNamespace="http://bataperu.com.pe/", IsWrapped=true)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bataperu.com.pe/", Order=0)]
        public AppBata_WS_Interfaces.BataTransac.Ent_MsgTransac HelloWorldResult;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(AppBata_WS_Interfaces.BataTransac.Ent_MsgTransac HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_update_transaction_guias", WrapperNamespace="http://bataperu.com.pe/", IsWrapped=true)]
    public partial class ws_update_transaction_guiasRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://bataperu.com.pe/")]
        public AppBata_WS_Interfaces.BataTransac.ValidateAcceso ValidateAcceso;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bataperu.com.pe/", Order=0)]
        public AppBata_WS_Interfaces.BataTransac.Ent_Fvdespc fvdespc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bataperu.com.pe/", Order=1)]
        public AppBata_WS_Interfaces.BataTransac.Ent_Scdddes scdddes;
        
        public ws_update_transaction_guiasRequest() {
        }
        
        public ws_update_transaction_guiasRequest(AppBata_WS_Interfaces.BataTransac.ValidateAcceso ValidateAcceso, AppBata_WS_Interfaces.BataTransac.Ent_Fvdespc fvdespc, AppBata_WS_Interfaces.BataTransac.Ent_Scdddes scdddes) {
            this.ValidateAcceso = ValidateAcceso;
            this.fvdespc = fvdespc;
            this.scdddes = scdddes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_update_transaction_guiasResponse", WrapperNamespace="http://bataperu.com.pe/", IsWrapped=true)]
    public partial class ws_update_transaction_guiasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bataperu.com.pe/", Order=0)]
        public AppBata_WS_Interfaces.BataTransac.Ent_MsgTransac ws_update_transaction_guiasResult;
        
        public ws_update_transaction_guiasResponse() {
        }
        
        public ws_update_transaction_guiasResponse(AppBata_WS_Interfaces.BataTransac.Ent_MsgTransac ws_update_transaction_guiasResult) {
            this.ws_update_transaction_guiasResult = ws_update_transaction_guiasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_errores_transaction", WrapperNamespace="http://bataperu.com.pe/", IsWrapped=true)]
    public partial class ws_errores_transactionRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://bataperu.com.pe/")]
        public AppBata_WS_Interfaces.BataTransac.ValidateAcceso ValidateAcceso;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bataperu.com.pe/", Order=0)]
        public string tip_error;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bataperu.com.pe/", Order=1)]
        public string msg;
        
        public ws_errores_transactionRequest() {
        }
        
        public ws_errores_transactionRequest(AppBata_WS_Interfaces.BataTransac.ValidateAcceso ValidateAcceso, string tip_error, string msg) {
            this.ValidateAcceso = ValidateAcceso;
            this.tip_error = tip_error;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_errores_transactionResponse", WrapperNamespace="http://bataperu.com.pe/", IsWrapped=true)]
    public partial class ws_errores_transactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bataperu.com.pe/", Order=0)]
        public AppBata_WS_Interfaces.BataTransac.Ent_MsgTransac ws_errores_transactionResult;
        
        public ws_errores_transactionResponse() {
        }
        
        public ws_errores_transactionResponse(AppBata_WS_Interfaces.BataTransac.Ent_MsgTransac ws_errores_transactionResult) {
            this.ws_errores_transactionResult = ws_errores_transactionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_get_location_dbf", WrapperNamespace="http://bataperu.com.pe/", IsWrapped=true)]
    public partial class ws_get_location_dbfRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://bataperu.com.pe/")]
        public AppBata_WS_Interfaces.BataTransac.ValidateAcceso ValidateAcceso;
        
        public ws_get_location_dbfRequest() {
        }
        
        public ws_get_location_dbfRequest(AppBata_WS_Interfaces.BataTransac.ValidateAcceso ValidateAcceso) {
            this.ValidateAcceso = ValidateAcceso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_get_location_dbfResponse", WrapperNamespace="http://bataperu.com.pe/", IsWrapped=true)]
    public partial class ws_get_location_dbfResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bataperu.com.pe/", Order=0)]
        public AppBata_WS_Interfaces.BataTransac.Ent_PathDBF[] ws_get_location_dbfResult;
        
        public ws_get_location_dbfResponse() {
        }
        
        public ws_get_location_dbfResponse(AppBata_WS_Interfaces.BataTransac.Ent_PathDBF[] ws_get_location_dbfResult) {
            this.ws_get_location_dbfResult = ws_get_location_dbfResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Bata_TransactionSoapChannel : AppBata_WS_Interfaces.BataTransac.Bata_TransactionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Bata_TransactionSoapClient : System.ServiceModel.ClientBase<AppBata_WS_Interfaces.BataTransac.Bata_TransactionSoap>, AppBata_WS_Interfaces.BataTransac.Bata_TransactionSoap {
        
        public Bata_TransactionSoapClient() {
        }
        
        public Bata_TransactionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Bata_TransactionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Bata_TransactionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Bata_TransactionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppBata_WS_Interfaces.BataTransac.HelloWorldResponse AppBata_WS_Interfaces.BataTransac.Bata_TransactionSoap.HelloWorld(AppBata_WS_Interfaces.BataTransac.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public AppBata_WS_Interfaces.BataTransac.Ent_MsgTransac HelloWorld(AppBata_WS_Interfaces.BataTransac.ValidateAcceso ValidateAcceso) {
            AppBata_WS_Interfaces.BataTransac.HelloWorldRequest inValue = new AppBata_WS_Interfaces.BataTransac.HelloWorldRequest();
            inValue.ValidateAcceso = ValidateAcceso;
            AppBata_WS_Interfaces.BataTransac.HelloWorldResponse retVal = ((AppBata_WS_Interfaces.BataTransac.Bata_TransactionSoap)(this)).HelloWorld(inValue);
            return retVal.HelloWorldResult;
        }
        
        public AppBata_WS_Interfaces.BataTransac.Ent_Fvdespc fvdespc() {
            return base.Channel.fvdespc();
        }
        
        public AppBata_WS_Interfaces.BataTransac.Ent_Scdddes scdddes() {
            return base.Channel.scdddes();
        }
        
        public AppBata_WS_Interfaces.BataTransac.Ent_PathDBF pathdbf() {
            return base.Channel.pathdbf();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppBata_WS_Interfaces.BataTransac.ws_update_transaction_guiasResponse AppBata_WS_Interfaces.BataTransac.Bata_TransactionSoap.ws_update_transaction_guias(AppBata_WS_Interfaces.BataTransac.ws_update_transaction_guiasRequest request) {
            return base.Channel.ws_update_transaction_guias(request);
        }
        
        public AppBata_WS_Interfaces.BataTransac.Ent_MsgTransac ws_update_transaction_guias(AppBata_WS_Interfaces.BataTransac.ValidateAcceso ValidateAcceso, AppBata_WS_Interfaces.BataTransac.Ent_Fvdespc fvdespc, AppBata_WS_Interfaces.BataTransac.Ent_Scdddes scdddes) {
            AppBata_WS_Interfaces.BataTransac.ws_update_transaction_guiasRequest inValue = new AppBata_WS_Interfaces.BataTransac.ws_update_transaction_guiasRequest();
            inValue.ValidateAcceso = ValidateAcceso;
            inValue.fvdespc = fvdespc;
            inValue.scdddes = scdddes;
            AppBata_WS_Interfaces.BataTransac.ws_update_transaction_guiasResponse retVal = ((AppBata_WS_Interfaces.BataTransac.Bata_TransactionSoap)(this)).ws_update_transaction_guias(inValue);
            return retVal.ws_update_transaction_guiasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppBata_WS_Interfaces.BataTransac.ws_errores_transactionResponse AppBata_WS_Interfaces.BataTransac.Bata_TransactionSoap.ws_errores_transaction(AppBata_WS_Interfaces.BataTransac.ws_errores_transactionRequest request) {
            return base.Channel.ws_errores_transaction(request);
        }
        
        public AppBata_WS_Interfaces.BataTransac.Ent_MsgTransac ws_errores_transaction(AppBata_WS_Interfaces.BataTransac.ValidateAcceso ValidateAcceso, string tip_error, string msg) {
            AppBata_WS_Interfaces.BataTransac.ws_errores_transactionRequest inValue = new AppBata_WS_Interfaces.BataTransac.ws_errores_transactionRequest();
            inValue.ValidateAcceso = ValidateAcceso;
            inValue.tip_error = tip_error;
            inValue.msg = msg;
            AppBata_WS_Interfaces.BataTransac.ws_errores_transactionResponse retVal = ((AppBata_WS_Interfaces.BataTransac.Bata_TransactionSoap)(this)).ws_errores_transaction(inValue);
            return retVal.ws_errores_transactionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppBata_WS_Interfaces.BataTransac.ws_get_location_dbfResponse AppBata_WS_Interfaces.BataTransac.Bata_TransactionSoap.ws_get_location_dbf(AppBata_WS_Interfaces.BataTransac.ws_get_location_dbfRequest request) {
            return base.Channel.ws_get_location_dbf(request);
        }
        
        public AppBata_WS_Interfaces.BataTransac.Ent_PathDBF[] ws_get_location_dbf(AppBata_WS_Interfaces.BataTransac.ValidateAcceso ValidateAcceso) {
            AppBata_WS_Interfaces.BataTransac.ws_get_location_dbfRequest inValue = new AppBata_WS_Interfaces.BataTransac.ws_get_location_dbfRequest();
            inValue.ValidateAcceso = ValidateAcceso;
            AppBata_WS_Interfaces.BataTransac.ws_get_location_dbfResponse retVal = ((AppBata_WS_Interfaces.BataTransac.Bata_TransactionSoap)(this)).ws_get_location_dbf(inValue);
            return retVal.ws_get_location_dbfResult;
        }
    }
}
